### ISSUE TITLE
"Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager."

### ISSUE THREAD

**Issue by Abhinandan-Kushwaha** [eufelipe/log-finance-react-native#1]
Hi Felipe Rosas👋

I am Abhinandan, the author and maintainer of the library - [react-native-gifted-charts](https://www.npmjs.com/package/react-native-gifted-charts) Thanks for using this library.

Your project **log-finance-react-native** is awesome!

When I open the **Reports** tab, the app crashes with this error - `"Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager."`

**Solution -**

Upon inspection, I found that the `react-native-webview` library was not installed. react-native-webview is required for rendering the Pie charts. Installing this library solved the issue! 🤗

**Comment by eufelipe** [comment]
Hi @Abhinandan-Kushwaha 😃 

I am pleased by your message, thank you very much =)

I have followed the lib docs by the book and it was working perfectly. But when I generated a new version and cleaned up the package.json, I ended up wrongly removing **react-native-webview**.
I was asking myself “why did I installed this?” 🤣 🤣 🤣 🤣 

This weekend I will generate a new version correcting this 🙃

Thank you very much

**Comment by Abhinandan-Kushwaha** [comment]
Cool @eufelipe 
Feels good to know I solved an issue 😂
